### PR TITLE
Added a filter that lets you change the capability required to view private replies.

### PR DESCRIPTION
**Pull request by fastlinemedia**
I went ahead and made the changes for issue #23. Let me know what you think!

### CODE REVIEW

**Comment by jrfnl** [comment]
Suggestion for efficiency:
* add a class property which holds the (original) value
* add an action to be run before the first time the value is used ( `init` ?) to filter the capacity
* use the class property rather than the function in the `user_can` calls

The result of the function is not supposed to change within a script run, so running the filter three times seems over the top.

**Comment by fastlinemedia** [comment]
Thanks for the feedback! Those are all great points. I'll go ahead and make the changes.

**Comment by fastlinemedia** [comment]
I just pushed the changes that were suggested. Let me know what you think!

**Comment by jrfnl** [comment]
Looks good to me ;-)

**Comment by pippinsplugins** [comment]
Sorry, never saw this PR. Good idea, I'll get it merged in!

**Comment by fastlinemedia** [comment]
Thanks!

**Pull request merged**
